In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv('online_retail.csv')
df
print("Dataset Shape:",df.shape)
df.head()

Dataset Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

Missing Values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Duplicate Rows:
5268

Data Types:
InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [6]:
df["Description"] = df["Description"].fillna("Unknown")
df["CustomerID"] = df["CustomerID"].fillna("Unknown")

print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [7]:
before = len(df)

df = df.drop_duplicates()

after = len(df)

print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)
print("Duplicates removed:", before - after)

Rows before removing duplicates: 541909
Rows after removing duplicates: 536641
Duplicates removed: 5268

In [10]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
print(df["Quantity"])
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors="coerce")
print(df["UnitPrice"])

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 536641, dtype: int64
0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 536641, dtype: float64

In [11]:
print(df.dtypes)

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID             object
Country                   str
dtype: object

In [12]:
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Invalid UnitPrice:", (df["UnitPrice"] <= 0).sum())

Negative Quantity: 10587
Invalid UnitPrice: 2512

In [13]:
df = df[df["Quantity"] > 0]
df = df[df["UnitPrice"] > 0]

In [15]:
df["Year"] = df["InvoiceDate"].dt.year
print(df)
df["Month"] = df["InvoiceDate"].dt.month
print(df)
df["Month_Name"] = df["InvoiceDate"].dt.month_name()
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice CustomerID         Country  Year  Month  \
0      2010-12-01 08:26:00       2.55    17850.0  United Kingdom  2010     12
1      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
2      2010-12-01 08:26:00       2.75    17850.0  United Kingdom  2010     12
3      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
4      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
...                    ...        ...        ...             ...   ...    ...
541904 2011-12-09 12:50:00       0.85    12680.0          France  2011     12
541905 2011-12-09 12:50:00       2.10    12680.0          France  2011     12
541906 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541907 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541908 2011-12-09 12:50:00       4.95    12680.0          France  2011     12

       Month_Name
0        December
1        December
2        December
3        December
4        December
...           ...
541904   December
541905   December
541906   December
541907   December
541908   December

[524878 rows x 11 columns]
       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice CustomerID         Country  Year  Month  \
0      2010-12-01 08:26:00       2.55    17850.0  United Kingdom  2010     12
1      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
2      2010-12-01 08:26:00       2.75    17850.0  United Kingdom  2010     12
3      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
4      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
...                    ...        ...        ...             ...   ...    ...
541904 2011-12-09 12:50:00       0.85    12680.0          France  2011     12
541905 2011-12-09 12:50:00       2.10    12680.0          France  2011     12
541906 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541907 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541908 2011-12-09 12:50:00       4.95    12680.0          France  2011     12

       Month_Name
0        December
1        December
2        December
3        December
4        December
...           ...
541904   December
541905   December
541906   December
541907   December
541908   December

[524878 rows x 11 columns]
       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice CustomerID         Country  Year  Month  \
0      2010-12-01 08:26:00       2.55    17850.0  United Kingdom  2010     12
1      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
2      2010-12-01 08:26:00       2.75    17850.0  United Kingdom  2010     12
3      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
4      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
...                    ...        ...        ...             ...   ...    ...
541904 2011-12-09 12:50:00       0.85    12680.0          France  2011     12
541905 2011-12-09 12:50:00       2.10    12680.0          France  2011     12
541906 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541907 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541908 2011-12-09 12:50:00       4.95    12680.0          France  2011     12

       Month_Name
0        December
1        December
2        December
3        December
4        December
...           ...
541904   December
541905   December
541906   December
541907   December
541908   December

[524878 rows x 11 columns]

In [19]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice CustomerID         Country  Year  Month  \
0      2010-12-01 08:26:00       2.55    17850.0  United Kingdom  2010     12
1      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
2      2010-12-01 08:26:00       2.75    17850.0  United Kingdom  2010     12
3      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
4      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
...                    ...        ...        ...             ...   ...    ...
541904 2011-12-09 12:50:00       0.85    12680.0          France  2011     12
541905 2011-12-09 12:50:00       2.10    12680.0          France  2011     12
541906 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541907 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541908 2011-12-09 12:50:00       4.95    12680.0          France  2011     12

       Month_Name  Revenue    Cost  Profit  Profit_Margin
0        December    15.30  10.710   4.590           30.0
1        December    20.34  14.238   6.102           30.0
2        December    22.00  15.400   6.600           30.0
3        December    20.34  14.238   6.102           30.0
4        December    20.34  14.238   6.102           30.0
...           ...      ...     ...     ...            ...
541904   December    10.20   7.140   3.060           30.0
541905   December    12.60   8.820   3.780           30.0
541906   December    16.60  11.620   4.980           30.0
541907   December    16.60  11.620   4.980           30.0
541908   December    14.85  10.395   4.455           30.0

[524878 rows x 15 columns]

In [18]:
df["Cost"] = df["Revenue"] * 0.70
df["Profit"] = df["Revenue"] - df["Cost"]

df["Profit_Margin"] = (
    df["Profit"] / df["Revenue"]
) * 100
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice CustomerID         Country  Year  Month  \
0      2010-12-01 08:26:00       2.55    17850.0  United Kingdom  2010     12
1      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
2      2010-12-01 08:26:00       2.75    17850.0  United Kingdom  2010     12
3      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
4      2010-12-01 08:26:00       3.39    17850.0  United Kingdom  2010     12
...                    ...        ...        ...             ...   ...    ...
541904 2011-12-09 12:50:00       0.85    12680.0          France  2011     12
541905 2011-12-09 12:50:00       2.10    12680.0          France  2011     12
541906 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541907 2011-12-09 12:50:00       4.15    12680.0          France  2011     12
541908 2011-12-09 12:50:00       4.95    12680.0          France  2011     12

       Month_Name  Revenue    Cost  Profit  Profit_Margin
0        December    15.30  10.710   4.590           30.0
1        December    20.34  14.238   6.102           30.0
2        December    22.00  15.400   6.600           30.0
3        December    20.34  14.238   6.102           30.0
4        December    20.34  14.238   6.102           30.0
...           ...      ...     ...     ...            ...
541904   December    10.20   7.140   3.060           30.0
541905   December    12.60   8.820   3.780           30.0
541906   December    16.60  11.620   4.980           30.0
541907   December    16.60  11.620   4.980           30.0
541908   December    14.85  10.395   4.455           30.0

[524878 rows x 15 columns]

In [20]:
print("========== AFTER CLEANING ==========")

print("Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

df.head()

========== AFTER CLEANING ==========
Shape: (524878, 15)

Missing Values:
InvoiceNo        0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
UnitPrice        0
CustomerID       0
Country          0
Year             0
Month            0
Month_Name       0
Revenue          0
Cost             0
Profit           0
Profit_Margin    0
dtype: int64

Duplicate Rows:
0

Data Types:
InvoiceNo                   str
StockCode                   str
Description                 str
Quantity                  int64
InvoiceDate      datetime64[us]
UnitPrice               float64
CustomerID               object
Country                     str
Year                      int32
Month                     int32
Month_Name                  str
Revenue                 float64
Cost                    float64
Profit                  float64
Profit_Margin           float64
dtype: object

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Month_Name,Revenue,Cost,Profit,Profit_Margin
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010,12,December,15.30,10.710,4.590,30.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,December,20.34,14.238,6.102,30.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010,12,December,22.00,15.400,6.600,30.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,December,20.34,14.238,6.102,30.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,December,20.34,14.238,6.102,30.0

In [24]:
df.to_csv("clean_dataset.csv", index=False)

print("clean_dataset.csv created successfully!")

clean_dataset.csv created successfully!

In [23]:
import os

print("File exists:", os.path.exists("clean_dataset.csv"))

File exists: True